config/routes.rb
Rails.application.routes.draw do
  
  root "tasks#index"

  resources :tasks

  resources :users, only: [:new, :create]

  #session
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  namespace :admin do
    resources :users do
      member do
        post "switch_authority"
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.task_status_enum(enum_value)
    I18n.t("activerecord.attributes.task.status.#{enum_value}")
  end
  def self.task_priority_enum(enum_value)
    I18n.t("activerecord.attributes.task.priority.#{enum_value}")
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :task
  belongs_to :tag
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true

  enum status: [task_status_enum(:pending), task_status_enum(:in_progress), task_status_enum(:done) ]
  enum priority: [task_priority_enum(:low), task_priority_enum(:medium), task_priority_enum(:high) ]

  paginates_per 30

  has_many :taggings
  has_many :tags, through: :taggings

  belongs_to :user

  def tag_items
    tags.map(&:name)
  end

  def tag_items=(names)
    self.tags = names.map{|item|
      Tag.where(name: item.strip).first_or_create! unless item.blank?}
  end

end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :check_last_admin
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: {:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
  
  has_many :tasks, dependent: :destroy

  has_secure_password
  enum authority: [ "member", "admin"]


  private
    def check_last_admin
      if User.admin.count == 1 && self.admin?
        errors.add(:base, I18n.t("user.last_admin"))
        throw :abort
      end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :find_user, only: [:show, :update, :destroy, :edit, :switch_authority]
  before_action :check_authority
  def index
    @users = User.page(params[:page]).per(5)
  end

  def show
    @q = @user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = I18n.t("user.create_success")
      redirect_to admin_users_path
    else
      render :new
      flash[:notice] = I18n.t("user.create_failed")
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = I18n.t("user.edit_success")
      redirect_to admin_users_path
    else
      render :edit 
      flash[:notice] = I18n.t("user.edit_failed")
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = I18n.t("user.delete_success")
    else
      flash[:notice] = I18n.t("user.delete_failed")
      flash[:notice] = @user.errors[:base].join if @user.errors[:base]
    end
    redirect_to admin_users_path
  end

  def switch_authority
    if @user.authority == "admin"
      User.admin.size <= 1 ? @user : @user.authority = "member"
    else
      @user.authority = "admin"
    end
    @user.save
    flash[:notice] = I18n.t("user.switch_complete")
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :login_verify, :set_ransack_obj
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  
  def set_ransack_obj
    @q = Task.ransack(params[:q])
  end

  def login_verify
    if session[:user_id].present? 
      @current_user = User.find(session[:user_id])
    else
      redirect_to login_path
    end
  end

  def admin_user?
    @current_user.authority == "admin"
  end

  def check_authority
    redirect_to tasks_path, notice: I18n.t("user.no_authority") if !admin_user?
  end

  private
  def record_not_found
    render file: 'public/404.html', status: 404, layout: false
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_verify
  before_action :find_user, only: [:create]
  def new
    @user = User.new
  end

  def create
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:notice] = I18n.t("session.login_success")
      redirect_to tasks_path
    else
      flash[:notice] = I18n.t("session.login_failed")
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = I18n.t("session.logout")
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find_by(email: params[:user][:email])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]
  before_action :tags_collection, only: [:new, :edit]
  skip_before_action :set_ransack_obj, only: [:index]

  def index
    @q = @current_user.tasks.includes(:user).ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page])

  end

  def show
  end

  def new
    @task = Task.new

  end

  def create
    @task = @current_user.tasks.build(task_params)
    if @task.save
      flash[:notice] = I18n.t("task.create_success")
      redirect_to tasks_path
    else
      render :new
      flash[:notice] = I18n.t("task.create_failed")
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:notice] = I18n.t("task.edit_success")
      redirect_to tasks_path
    else
      render :edit 
      flash[:notice] = I18n.t("task.edit_failed")
    end
  end

  def destroy
    if @task.destroy
      flash[:notice] = I18n.t("task.delete_success")
    else
      flash[:notice] = I18n.t("task.delete_failed")
    end
    redirect_to tasks_path
  end

  private
  
  def task_params
    params.require(:task).permit(:name,
                                 :description, 
                                 :priority, 
                                 :status, 
                                 :start_at, 
                                 :end_at,
                                 { tag_items: [] }
                                 )
  end

  def find_task
    @task = Task.find(params[:id])
  end

  def tags_collection
    @tags = []
    @current_user.tasks.each do |task|
      task.tags.each do |tag|
        @tags << tag.name
      end
    end
    @tags.uniq!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout false
  skip_before_action :login_verify

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = I18n.t("user.create_success")
      session[:user_id] = @user.id
      redirect_to tasks_path
    else
      render :new
      flash[:notice] = I18n.t("user.create_failed")
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/admin/users/edit.html.erb
<h1><%= t("user.edit") %></h1>
<%= form_with model: @user, url: admin_user_path, local: true do |f| %>
  <% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="form-group">
    <%= f.label :name, t("user.name"), class:"form-label form_title"  %>
    <%= f.text_field :name, id: "user_name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password, t("users.password"), class:"form-label form_title" %>
    <%= f.password_field :password, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :email, t("users.email") %>
    <%= f.text_field :email, class: "form-control"%>
  </div>    
    <%= f.submit t("button.submit"), class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/admin/users/index.html.erb

<%= link_to t("user.create_user"), new_admin_user_path, class: "new-link", class: "new-link btn btn-primary" %>
<table class="table table-striped">
  <thead>
    <td><%= t("user.authority") %></td>
    <td><%= t("user.name") %></td>
    <td><%= t("user.email") %></td>
    <td><%= t("user.created_at") %></td>
    <td><%= t("user.tasks_count") %></td>
    <td></td>
  </thead>
  <tbody>
    <% @users.each do |user|%>
      <tr id=<%= user.id %>>
        <td>
          <%= user.authority %>
        </td>
        <td>
          <%= link_to user.name, admin_user_path(user) %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.created_at %>
        </td>
        <td>
          <%= user.tasks.count %>
        </td>
        <td>
        <%= link_to t("user.switch_authority"), switch_authority_admin_user_path(user.id), data: {method: "POST", confirm: t("user.switch_authority_confirm")} %>
        </td>
        <td>
          <%= link_to t("user.edit_user"), edit_admin_user_path(user) %>
          <%= link_to t("user.delete_user"), admin_user_path(user), data: {method: "DELETE", confirm: t("user.delete_confirm")} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/admin/users/new.html.erb
<h1><%= t("user.create_user") %></h1>
<%= form_with model: @user, url: admin_users_path, local: true do |f| %>
  <% if @user.errors.any? %>
  <ul>
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="form-group">
    <%= f.label :name, t("user.name"), class:"form-label form_title"  %>
    <%= f.text_field :name, id: "user_name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password, t("users.password"), class:"form-label form_title" %>
    <%= f.password_field :password, id: "user_password", class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :email, t("users.email") %>
    <%= f.text_field :email, id: "user_email", class: "form-control"%>
  </div>    
    <%= f.submit t("button.submit"), class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<div class="container">
  <table class="table table-borderless table-hover w-auto">
    <tr>
      <th><%= t("user.name") %></th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th><%= t("user.email") %></th> 
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th><%= t("user.tasks_count") %></th> 
      <td><%= @user.tasks.count %></td>
    </tr>
  </table> 
  <table class="table table-hover ">
    <thead class="table-warning">
      <tr>
        <th scope="col"><%= t("task.name") %></th>
        <th scope="col">
          <%= sort_link(@q, :priority, t("task.priority"), default_order: :desc) %>
        </th>
        <th scope="col">
          <%= sort_link(@q, :status, t("task.status"), default_order: :desc) %>
        </th>
        <th scope="col">
          <%= sort_link(@q, :start_at, t("task.start_at"), default_order: :desc) %>
        </th>
        <th scope="col">
          <%= sort_link(@q, :created_at, t("task.created_at"), default_order: :desc) %>
        </th>
        <th scope="col">
          <%= sort_link(@q, :end_at, t("task.end_at"), default_order: :desc) %>
        </th>
        <th scope="col"></th>
      </tr>
    </thead>
    <div class="task_section">
      <% @tasks.each do |task| %>
        <tbody>
          <tr>
          <td><%= link_to task.name, task_path(task.id) %></td>
          <td><%= task.priority %></td>
          <td><%= task.status %></td>
          <td><%= task.start_at.strftime("%B %d, %Y") if task.start_at.present?%></td>
          <td><%= task.created_at.strftime("%B %d, %Y") %></td>
          <td><%= task.end_at.strftime("%B %d, %Y") if task.end_at.present?%></td>
          </tr>
        </tbody>
      <% end %>
    </div>
  </table>
  <%= paginate @tasks %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackendTrain</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'share/navbar' %>
    <%= render 'share/flash' %>

    <div class="container main_bg">
      <%= yield %>
    </div>
  </body>
</html>

app/views/share/_flash.html.erb
<%if notice %>
  <div class="message_notice alert alert-danger" role="alert" data-controller="notice" data-target="notice.message">
    <div>
      <i class="fas fa-paw"></i> 
      <%= notice %>
    </div>
    <a class="close" data-action="notice#close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>    

app/views/share/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "My Task", root_path, class: "navbar-brand" %>
    <% if @current_user.present? %>
      <div class="navbar_search nav-item">
        <%= search_form_for @q do |f| %>
          <%= f.label :name_cont, t("task.name") %>
          <%= f.search_field :name_cont %>
          <%= f.label :status_eq, t("task.status") %>
          <%= f.select :status_eq, Task.statuses.to_a, :include_blank => true, class: "form-select-sm" %>
          <%= f.label :priority_eq, t("task.priority") %>
          <%= f.select :priority_eq, Task.priorities.to_a, :include_blank => true, class: "form-select-sm" %>
          <%= f.submit t("search.submit_btn") %>
        <% end %>
      </div>
      <div class="nav-item">
        <%= link_to t("session.logout"), logout_path, method: "delete" %>
      </div>
      <div class="nav-item">
        <%= link_to t("admin_page"), admin_users_path %>
      </div>
    <% end %>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with model: task, local: true do |f| %>
  <% if task.errors.any? %>
  <ul>
    <% task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="form_section">
    <div>
      <%= f.label :name, t("task.name"), class:"form-label form_title"  %>
      <%= f.text_field :name, id: "task_name", class: "form-control" %>
    </div>
    <div>
      <%= f.label :description, t("task.description"), class:"form-label form_title"  %>
      <%= f.text_area :description, id: "task_description", class: "form-control", row: "4" %>
    </div>
    <div>
      <%= f.label :start_at, t("task.start_at"), class:"form-label form_title"  %>
      <%= f.datetime_field :start_at, id: "task_start", class: "form-control" %>
    </div>
    <div>
      <%= f.label :end_at, t("task.end_at"), class:"form-label form_title"  %>
      <%= f.datetime_field :end_at, id: "task_end", class: "form-control" %>
    </div>
    <div>
      <%= f.label :status, t("task.status"), class:"form-label form_title"  %>
      <%= f.select :status, Task.statuses.keys, {:include_blank => true}, id: "task_status", class: "form-control" %>
    </div>
    <div>
      <%= f.label :priority, t("task.priority"), class:"form-label form_title"  %>
      <%= f.select :priority, Task.priorities.keys, {:include_blank => true}, id: "task_priority", class: "form-control" %>
    </div>
    <div data-controller="task">
      <%= f.label :priority, t("tag"), class:"form-label form_title"  %>
      <%= f.select :tag_items, @tags,{:include_hidden => false}, {:multiple => true, :class => "form-control tag_select"} %>
    </div>
    <div>
      <%= f.submit t("button.submit"), class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>修改任務</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
  
<h1><%= t("task.task_list") %></h1>
<%= link_to t("task.create_task"), new_task_path, class: "btn btn-primary" %>
<div class="input-group main_search">
  <%= search_form_for @q do |f| %>
    <%= f.label :name_cont, t("task.name") %>
    <%= f.search_field :name_cont, class: "" %>
    <%= f.label :status_eq, t("task.status") %>
    <%= f.select :status_eq, Task.statuses.to_a, {:include_blank => true}, class: "form-select-sm" %>
    <%= f.label :priority_eq, t("task.priority") %>
    <%= f.select :priority_eq, Task.priorities.to_a, {:include_blank => true}, class: "form-select-sm" %>
    <%= f.label :tags_name_cont, t("tag") %>
    <%= f.search_field :tags_name_cont%>
    <%= f.submit t("search.submit_btn"), class: "btn btn-secondary" %>
  <% end %>
</div>
<table class="table table-hover ">
    <thead class="table-warning">
        <tr>
          <th scope="col"><%= t("task.name") %></th>
          <th scope="col">
            <%= sort_link(@q, :priority, t("task.priority"), default_order: :desc) %>
          </th>
          <th scope="col">
            <%= sort_link(@q, :status, t("task.status"), default_order: :desc) %>
          </th>
          <th scope="col">
            <%= t("tag") %>
          </th>
          <th scope="col">
            <%= sort_link(@q, :start_at, t("task.start_at"), default_order: :desc) %>
          </th>
          <th scope="col">
            <%= sort_link(@q, :created_at, t("task.created_at"), default_order: :desc) %>
          </th>
          <th scope="col">
            <%= sort_link(@q, :end_at, t("task.end_at"), default_order: :desc) %>
          </th>
          <th scope="col"></th>
        </tr>
    </thead>
  <div class="task_section">
    <% @tasks.each do |task| %>
      <tbody>
          <tr>
            <td><%= link_to task.name, task_path(task.id) %></td>
            <td><%= task.priority %></td>
            <td><%= task.status %></td>
            <td>
              <% task.tags.each do |tag| %>
                <%= tag.name %>
              <% end %>
            </td>
            <td><%= task.start_at.strftime("%B %d, %Y") if task.start_at.present?%></td>
            <td><%= task.created_at.strftime("%B %d, %Y") %></td>
            <td><%= task.end_at.strftime("%B %d, %Y") if task.end_at.present?%></td>
            <td>
              <%= link_to t("task.edit_task"), edit_task_path(task.id) %>
              <%= link_to t("task.delete_task"), task_path(task.id), method: "delete" %>
            </td>
          </tr>
      </tbody>
    <% end %>
  </div>
</table>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1><%= t("task.create_task") %></h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="container">
  <table class="table table-borderless table-hover w-auto">
    <tr>
      <th><%= t("task.name") %></th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th><%= t("task.description") %></th> 
      <td><%= @task.description %></td>
    </tr>
    <tr>
      <th><%= t("task.start_at") %></th>
      <td><%= @task.start_at %></td>
    </tr>
    <tr>
      <th><%= t("task.end_at") %></th>
      <td><%= @task.end_at %></td>
    </tr>
    <tr>
      <th><%= t("task.status") %></th>
      <td><%= @task.status %></td>
    </tr>
    <tr>
      <th><%= t("task.priority") %></th>
      <td><%= @task.priority %></td>
    </tr>
    <tr>
      <th><%= t("tag") %></th>
      <td>
        <% @task.tags.each do |tag| %>
          <%= tag.name %>
        <% end %>
      </td>  
    </tr>
  </table> 
</div>

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |f| %>
  <% if user.errors.any? %>
  <ul>
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="form-group">
    <%= f.label :name, t("user.name"), class:"form-label form_title"  %>
    <%= f.text_field :name, id: "user_name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password, t("users.password"), class:"form-label form_title" %>
    <%= f.password_field :password, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :email, t("users.email") %>
    <%= f.text_field :email, class: "form-control"%>
  </div>    
    <%= f.submit t("button.submit"), class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/users/new.html.erb

<!DOCTYPE html>
<html>
  <head>
    <title>BackendTrain</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'share/flash' %>
    <div class="container main_bg">
      <%= render "form", user: @user %>
    </div>
  </body>
</html>